# Generated by Django 2.0.7 on 2018-07-19 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_app', '0004_auto_20180719_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
